### ISSUE TITLE
def f(self, x)

### ISSUE THREAD

**Issue by mmclineew** [AntonEvmenenko/2d_geometric_constraint_solver#1]
In "slover.py"
 "def f(self, x):
       self.geometry_from_vars(x)
      result = 0
     if not self.active_point is None:
            result = distance_p2p(self.active_point, self.active_point_copy)"
Why is the distance between active_point and active_point_copy used as the return value, can you give a practical example to explain?

**Comment by AntonEvmenenko** [comment]
Hey @mmclineew,

Thank you for your interest in my project :)

I'm happy to help and explain, but your question is a bit strange tbh. Do you understand the meaning of the `f` function? Is it clear for you the `active_point` is the point you're moving with the mouse?
