### ISSUE TITLE
Constant lenght constraint

### ISSUE THREAD

**Issue by ochoadavid** [AntonEvmenenko/2d_geometric_constraint_solver#2]
Hi!

I just found this repository and your blog. Thanks for sharing, great work.

I'm trying to implement a simple solver for 2D mechanisms, and I think it may be possible to extend and specialize your solver to that end. So, I wanted to ask: although is declared I see that "constant length" constrain is implemented, but commented in the code. ¿Could you be willing to share me your advances and work in progress? So, maybe, I could advance from there. 

Thanks,
David Ochoa

**Comment by AntonEvmenenko** [comment]
Hi David,

> I just found this repository and your blog. Thanks for sharing, great work.

Thanks for your kind words! 🙏 

> I'm trying to implement a simple solver for 2D mechanisms, and I think it may be possible to extend and specialize your solver to that end. So, I wanted to ask: although is declared I see that "constant length" constrain is implemented, but commented in the code. ¿Could you be willing to share me your advances and work in progress? So, maybe, I could advance from there.

Well, you are right, the length constraint is implemented in the solver, but I was too lazy to add it to the GUI 😄 However, despite the fact you can not add such constraints via the GUI, you can easily add them programmatically. I just added a new [branch](https://github.com/AntonEvmenenko/2d_geometric_constraint_solver/tree/length_constraint) with a simple example, try it out.

But, if you're interested in adding such constraints via the GUI, it's a different thing. Let me know.

P.S. I just realized that I forgot to include some important information into the README: you can move around the canvas by dragging while holding mouse wheel button down. It's fixed now, but still FYI
